#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export EXTERNAL_BASE_URL="${EXTERNAL_BASE_URL:-http://118.24.135.235}"
export SERVICE_NAME="${SERVICE_NAME:-aotu-gpt}"
export BACKGROUND_SERVICE_NAME="${BACKGROUND_SERVICE_NAME:-aotu-gpt-worker}"
export NGINX_SITE_NAME="${NGINX_SITE_NAME:-aotu-gpt}"

# Tencent lightweight instance profile: Chengdu, 2 vCPU, 2GB RAM, 40GB SSD, 3Mbps.
export DEFAULT_WEB_CONCURRENCY="${DEFAULT_WEB_CONCURRENCY:-2}"
export DEFAULT_DB_POOL_SIZE="${DEFAULT_DB_POOL_SIZE:-8}"
export DEFAULT_DB_MAX_OVERFLOW="${DEFAULT_DB_MAX_OVERFLOW:-4}"
export DEFAULT_DB_POOL_TIMEOUT="${DEFAULT_DB_POOL_TIMEOUT:-10}"
export DEFAULT_ENABLE_STARTUP_HEAVY_SYNC="${DEFAULT_ENABLE_STARTUP_HEAVY_SYNC:-false}"
export DEFAULT_ENABLE_BACKGROUND_WORKERS="${DEFAULT_ENABLE_BACKGROUND_WORKERS:-false}"
export ENABLE_SEPARATE_BACKGROUND_SERVICE="${ENABLE_SEPARATE_BACKGROUND_SERVICE:-1}"
export DEFAULT_REQUEST_LOG_QUEUE_WORKER_COUNT="${DEFAULT_REQUEST_LOG_QUEUE_WORKER_COUNT:-1}"
export DEFAULT_REQUEST_LOG_QUEUE_BATCH_SIZE="${DEFAULT_REQUEST_LOG_QUEUE_BATCH_SIZE:-100}"
export DEFAULT_TOKEN_FINALIZE_WORKER_COUNT="${DEFAULT_TOKEN_FINALIZE_WORKER_COUNT:-1}"
export DEFAULT_TOKEN_FINALIZE_QUEUE_SIZE="${DEFAULT_TOKEN_FINALIZE_QUEUE_SIZE:-5000}"
export DEFAULT_WORKER_THREADPOOL_TOKENS="${DEFAULT_WORKER_THREADPOOL_TOKENS:-80}"
export DEFAULT_UPSTREAM_JSON_CLIENT="${DEFAULT_UPSTREAM_JSON_CLIENT:-aiohttp}"
export DEFAULT_UPSTREAM_STREAM_CLIENT="${DEFAULT_UPSTREAM_STREAM_CLIENT:-aiohttp}"
export DEFAULT_UPSTREAM_POOL_TIMEOUT_S="${DEFAULT_UPSTREAM_POOL_TIMEOUT_S:-10}"
export DEFAULT_GLOBAL_MAX_ACTIVE_REQUESTS="${DEFAULT_GLOBAL_MAX_ACTIVE_REQUESTS:-100}"
export DEFAULT_GLOBAL_MAX_ACTIVE_STREAMS="${DEFAULT_GLOBAL_MAX_ACTIVE_STREAMS:-40}"
export DEFAULT_API_KEY_MAX_ACTIVE_REQUESTS="${DEFAULT_API_KEY_MAX_ACTIVE_REQUESTS:-40}"
export DEFAULT_API_KEY_MAX_ACTIVE_STREAMS="${DEFAULT_API_KEY_MAX_ACTIVE_STREAMS:-20}"
export DEFAULT_ACCOUNT_MAX_ACTIVE_REQUESTS="${DEFAULT_ACCOUNT_MAX_ACTIVE_REQUESTS:-60}"
export DEFAULT_ACCOUNT_MAX_ACTIVE_STREAMS="${DEFAULT_ACCOUNT_MAX_ACTIVE_STREAMS:-20}"
export DEFAULT_PROVIDER_MAX_ACTIVE_REQUESTS="${DEFAULT_PROVIDER_MAX_ACTIVE_REQUESTS:-40}"
export DEFAULT_PROVIDER_MAX_ACTIVE_STREAMS="${DEFAULT_PROVIDER_MAX_ACTIVE_STREAMS:-20}"
export DEFAULT_PROBE_RATE_LIMIT_PER_MINUTE="${DEFAULT_PROBE_RATE_LIMIT_PER_MINUTE:-4}"
export DEFAULT_PROBE_TYPE_RATE_LIMIT_PER_MINUTE="${DEFAULT_PROBE_TYPE_RATE_LIMIT_PER_MINUTE:-4}"

exec bash "$PROJECT_ROOT/start_aliyun.sh" "$@"
