#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export EXTERNAL_BASE_URL="${EXTERNAL_BASE_URL:-http://118.24.135.235}"
export HEALTH_URL="${HEALTH_URL:-http://127.0.0.1:8000/ready}"
export SERVICE_NAME="${SERVICE_NAME:-aotu-gpt}"
export BACKGROUND_SERVICE_NAME="${BACKGROUND_SERVICE_NAME:-aotu-gpt-worker}"
export NGINX_SITE_NAME="${NGINX_SITE_NAME:-aotu-gpt}"

export DEFAULT_WEB_CONCURRENCY="${DEFAULT_WEB_CONCURRENCY:-2}"
export DEFAULT_DB_POOL_SIZE="${DEFAULT_DB_POOL_SIZE:-8}"
export DEFAULT_DB_MAX_OVERFLOW="${DEFAULT_DB_MAX_OVERFLOW:-4}"
export DEFAULT_DB_POOL_TIMEOUT="${DEFAULT_DB_POOL_TIMEOUT:-10}"
export DEFAULT_ENABLE_BACKGROUND_WORKERS="${DEFAULT_ENABLE_BACKGROUND_WORKERS:-false}"
export ENABLE_SEPARATE_BACKGROUND_SERVICE="${ENABLE_SEPARATE_BACKGROUND_SERVICE:-1}"
export DEFAULT_REQUEST_LOG_QUEUE_WORKER_COUNT="${DEFAULT_REQUEST_LOG_QUEUE_WORKER_COUNT:-1}"
export DEFAULT_TOKEN_FINALIZE_WORKER_COUNT="${DEFAULT_TOKEN_FINALIZE_WORKER_COUNT:-1}"
export DEFAULT_WORKER_THREADPOOL_TOKENS="${DEFAULT_WORKER_THREADPOOL_TOKENS:-80}"
export DEFAULT_UPSTREAM_MAX_CONNECTIONS="${DEFAULT_UPSTREAM_MAX_CONNECTIONS:-240}"
export DEFAULT_UPSTREAM_MAX_KEEPALIVE_CONNECTIONS="${DEFAULT_UPSTREAM_MAX_KEEPALIVE_CONNECTIONS:-80}"

exec bash "$PROJECT_ROOT/update_aliyun.sh" "$@"
