-- 迁移说明：新增提供商内容完整性防护、信任等级和日志留证字段。
-- 执行前请按生产规范完成数据库备份。

ALTER TABLE providers
    ADD COLUMN IF NOT EXISTS trust_level TEXT NOT NULL DEFAULT 'standard',
    ADD COLUMN IF NOT EXISTS content_integrity_status TEXT NOT NULL DEFAULT 'unknown',
    ADD COLUMN IF NOT EXISTS content_integrity_score INTEGER NOT NULL DEFAULT 80,
    ADD COLUMN IF NOT EXISTS content_violation_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_content_violation_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS content_guard_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS buffer_stream_for_guard BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS circuit_state TEXT NOT NULL DEFAULT 'closed',
    ADD COLUMN IF NOT EXISTS circuit_opened_at TIMESTAMP;

ALTER TABLE provider_models
    ADD COLUMN IF NOT EXISTS circuit_state TEXT NOT NULL DEFAULT 'closed',
    ADD COLUMN IF NOT EXISTS circuit_opened_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS content_integrity_status TEXT NOT NULL DEFAULT 'unknown',
    ADD COLUMN IF NOT EXISTS content_probe_last_passed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS content_probe_last_failed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS content_probe_failure_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS content_probe_results_json TEXT;

ALTER TABLE request_logs
    ADD COLUMN IF NOT EXISTS content_guard_result TEXT,
    ADD COLUMN IF NOT EXISTS content_guard_risk_level TEXT,
    ADD COLUMN IF NOT EXISTS content_guard_categories_json TEXT,
    ADD COLUMN IF NOT EXISTS content_guard_reason TEXT,
    ADD COLUMN IF NOT EXISTS content_guard_action TEXT,
    ADD COLUMN IF NOT EXISTS content_guard_excerpt TEXT;

ALTER TABLE app_settings
    ADD COLUMN IF NOT EXISTS content_guard_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS content_guard_precheck_auto_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS content_guard_block_on_high_risk BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS content_guard_probe_interval_sec INTEGER NOT NULL DEFAULT 3600,
    ADD COLUMN IF NOT EXISTS content_guard_max_scan_bytes INTEGER NOT NULL DEFAULT 16384,
    ADD COLUMN IF NOT EXISTS content_guard_stream_buffer_max_bytes INTEGER NOT NULL DEFAULT 16384,
    ADD COLUMN IF NOT EXISTS content_guard_low_trust_requires_buffer BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS content_guard_rules_json TEXT NOT NULL DEFAULT '';

UPDATE providers
SET trust_level = 'standard'
WHERE trust_level IS NULL OR trust_level NOT IN ('official', 'trusted', 'standard', 'low', 'blocked');

UPDATE providers
SET content_integrity_status = 'unknown'
WHERE content_integrity_status IS NULL OR content_integrity_status NOT IN ('unknown', 'passed', 'degraded', 'blocked');

UPDATE provider_models
SET content_integrity_status = 'unknown'
WHERE content_integrity_status IS NULL OR content_integrity_status NOT IN ('unknown', 'passed', 'degraded', 'blocked');

CREATE INDEX IF NOT EXISTS ix_providers_content_integrity_status ON providers (content_integrity_status);
CREATE INDEX IF NOT EXISTS ix_providers_trust_level ON providers (trust_level);
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_result ON request_logs (content_guard_result);
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_risk_created_provider
    ON request_logs (content_guard_risk_level, created_at, provider_id)
    WHERE content_guard_risk_level IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_result_created_provider
    ON request_logs (content_guard_result, created_at, provider_id)
    WHERE content_guard_result IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_provider_created_result
    ON request_logs (provider_id, created_at, content_guard_result)
    WHERE content_guard_result IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_provider_created_risk
    ON request_logs (provider_id, created_at, content_guard_risk_level)
    WHERE content_guard_risk_level IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_logs_content_guard_trace_id
    ON request_logs (trace_id)
    WHERE content_guard_result IS NOT NULL OR content_guard_risk_level IS NOT NULL;

CREATE TABLE IF NOT EXISTS request_content_guard_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    provider_id INTEGER,
    provider_name TEXT,
    provider_model_id INTEGER,
    model_name TEXT,
    requested_model TEXT,
    request_path TEXT,
    is_stream BOOLEAN,
    guard_stage TEXT NOT NULL,
    guard_result TEXT,
    risk_level TEXT,
    matched_categories_json TEXT,
    matched_rules_json TEXT,
    reason TEXT,
    action TEXT,
    excerpt TEXT,
    provider_status_after TEXT,
    diagnostics_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE request_content_guard_events
    ADD COLUMN IF NOT EXISTS provider_id INTEGER,
    ADD COLUMN IF NOT EXISTS provider_name TEXT,
    ADD COLUMN IF NOT EXISTS provider_model_id INTEGER,
    ADD COLUMN IF NOT EXISTS model_name TEXT,
    ADD COLUMN IF NOT EXISTS requested_model TEXT,
    ADD COLUMN IF NOT EXISTS request_path TEXT,
    ADD COLUMN IF NOT EXISTS is_stream BOOLEAN,
    ADD COLUMN IF NOT EXISTS diagnostics_json TEXT;

CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_trace_id ON request_content_guard_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_id ON request_content_guard_events (provider_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_model_id ON request_content_guard_events (provider_model_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_model_name ON request_content_guard_events (model_name);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_request_path ON request_content_guard_events (request_path);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_is_stream ON request_content_guard_events (is_stream);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_guard_stage ON request_content_guard_events (guard_stage);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_guard_result ON request_content_guard_events (guard_result);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_risk_level ON request_content_guard_events (risk_level);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_created_at ON request_content_guard_events (created_at);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_created_result
    ON request_content_guard_events (provider_id, created_at, guard_result)
    WHERE guard_result IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_risk_provider_created
    ON request_content_guard_events (risk_level, provider_id, created_at)
    WHERE risk_level IS NOT NULL;

CREATE TABLE IF NOT EXISTS health_probe_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL,
    run_id TEXT,
    provider_id INTEGER,
    provider_model_id INTEGER,
    model_name TEXT,
    probe_type TEXT NOT NULL,
    endpoint_path TEXT,
    protocol_type TEXT,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    status_code INTEGER,
    latency_ms INTEGER,
    error_code TEXT,
    capability_result_json TEXT,
    content_guard_result_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE health_probe_events
    ADD COLUMN IF NOT EXISTS request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_health_probe_events_request_log_id ON health_probe_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_run_id ON health_probe_events (run_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_provider_id ON health_probe_events (provider_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_provider_model_id ON health_probe_events (provider_model_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_probe_type ON health_probe_events (probe_type);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_success ON health_probe_events (success);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_error_code ON health_probe_events (error_code);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_created_at ON health_probe_events (created_at);
