-- Ensure typed logging event IDs are generated in PostgreSQL environments where
-- earlier migrations created plain INTEGER PRIMARY KEY columns.

DO $$
DECLARE
    table_name TEXT;
    sequence_name TEXT;
    max_existing_id BIGINT;
BEGIN
    FOREACH table_name IN ARRAY ARRAY[
        'request_auth_events',
        'request_validation_events',
        'request_model_permission_events',
        'request_route_decision_events',
        'request_provider_attempt_events',
        'request_upstream_response_events',
        'request_stream_events',
        'request_error_response_events',
        'request_content_guard_events',
        'request_billing_events',
        'exception_events',
        'health_check_runs',
        'health_probe_events',
        'token_finalize_events',
        'billing_process_events',
        'background_job_events',
        'user_operation_audit_logs',
        'asset_events',
        'alert_events',
        'alert_subscriptions'
    ]
    LOOP
        IF to_regclass(table_name) IS NULL THEN
            CONTINUE;
        END IF;

        IF pg_get_serial_sequence(table_name, 'id') IS NULL THEN
            EXECUTE format('ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', table_name);
        END IF;

        sequence_name := pg_get_serial_sequence(table_name, 'id');
        IF sequence_name IS NOT NULL THEN
            EXECUTE format('SELECT COALESCE(MAX(id), 0) FROM %I', table_name) INTO max_existing_id;
            PERFORM setval(sequence_name::regclass, GREATEST(max_existing_id + 1, 1), FALSE);
        END IF;
    END LOOP;
END $$;
