-- Add PostgreSQL schema for alert events now managed by the unified logging center.

CREATE TABLE IF NOT EXISTS alert_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_key TEXT NOT NULL UNIQUE,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'warning',
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    payload_json TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    first_seen_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    last_seen_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    last_notified_at TIMESTAMP,
    acknowledged_at TIMESTAMP,
    resolved_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    updated_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE INDEX IF NOT EXISTS ix_alert_events_alert_key ON alert_events (alert_key);
CREATE INDEX IF NOT EXISTS ix_alert_events_alert_type ON alert_events (alert_type);
CREATE INDEX IF NOT EXISTS ix_alert_events_status_last_seen ON alert_events (status, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS alert_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER NOT NULL UNIQUE REFERENCES user_accounts(id) ON DELETE CASCADE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    delivery_channel TEXT NOT NULL DEFAULT 'in_app',
    notify_provider_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    notify_api_key_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    notify_account_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    notify_failure_rate_alerts BOOLEAN NOT NULL DEFAULT TRUE,
    browser_notifications_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    poll_interval_seconds INTEGER NOT NULL DEFAULT 30,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    updated_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE INDEX IF NOT EXISTS ix_alert_subscriptions_user_account_id ON alert_subscriptions (user_account_id);

ALTER TABLE app_settings
    ADD COLUMN IF NOT EXISTS alert_event_retention_days INTEGER NOT NULL DEFAULT 180;
