-- Extend typed logging details for diagnostics without rebuilding existing log tables.

ALTER TABLE request_logs
    ADD COLUMN IF NOT EXISTS content_guard_confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS content_guard_score_delta INTEGER;

CREATE TABLE IF NOT EXISTS request_auth_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    auth_result TEXT NOT NULL,
    api_client_key_id INTEGER,
    api_client_key_prefix TEXT,
    user_account_id INTEGER,
    remaining_tokens INTEGER,
    remaining_requests_daily INTEGER,
    remaining_cost_daily DOUBLE PRECISION,
    policy_snapshot_json TEXT,
    error_code TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_validation_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    validation_stage TEXT NOT NULL,
    passed BOOLEAN NOT NULL DEFAULT TRUE,
    limit_value INTEGER,
    actual_value INTEGER,
    request_body_summary_json TEXT,
    error_code TEXT,
    safe_detail_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_model_permission_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    requested_model TEXT,
    resolved_model TEXT,
    endpoint_path TEXT,
    required_capabilities_json TEXT,
    permission_result TEXT NOT NULL,
    reason_details_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_route_decision_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    route_round INTEGER NOT NULL DEFAULT 1,
    route_policy TEXT,
    candidate_count INTEGER,
    selected_provider_id INTEGER,
    selected_provider_model_id INTEGER,
    sticky_hit BOOLEAN,
    excluded_summary_json TEXT,
    diagnostics_json TEXT,
    retry_wait_ms INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_provider_attempt_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    attempt_index INTEGER NOT NULL DEFAULT 1,
    provider_id INTEGER,
    provider_name TEXT,
    provider_model_id INTEGER,
    actual_model TEXT,
    endpoint_path TEXT,
    protocol_type TEXT,
    capacity_lease_acquired BOOLEAN,
    result TEXT NOT NULL,
    status_code INTEGER,
    latency_ms INTEGER,
    upstream_request_id TEXT,
    error_code TEXT,
    retryable BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_upstream_response_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    provider_attempt_event_id INTEGER REFERENCES request_provider_attempt_events(id) ON DELETE SET NULL,
    trace_id TEXT,
    status_code INTEGER,
    upstream_request_id TEXT,
    finish_reason TEXT,
    usage_json TEXT,
    response_summary_json TEXT,
    response_text_excerpt TEXT,
    response_body_truncated BOOLEAN,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_stream_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    stream_result TEXT NOT NULL,
    first_token_latency_ms INTEGER,
    ttfb_ms INTEGER,
    duration_ms INTEGER,
    chunk_count INTEGER,
    captured_text_bytes INTEGER,
    sse_error_sent BOOLEAN,
    done_sent BOOLEAN,
    disconnect_status_code INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_error_response_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    status_code INTEGER,
    error_type TEXT,
    error_code TEXT,
    public_message TEXT,
    category TEXT,
    retryable BOOLEAN,
    recoverable BOOLEAN,
    required_endpoint TEXT,
    missing_capability TEXT,
    diagnostic_sample_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS request_content_guard_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    provider_id INTEGER,
    provider_name TEXT,
    provider_model_id INTEGER,
    model_name TEXT,
    requested_model TEXT,
    request_path TEXT,
    is_stream BOOLEAN,
    guard_stage TEXT NOT NULL,
    guard_result TEXT,
    risk_level TEXT,
    matched_categories_json TEXT,
    matched_rules_json TEXT,
    reason TEXT,
    action TEXT,
    excerpt TEXT,
    provider_status_after TEXT,
    confidence DOUBLE PRECISION,
    score_delta INTEGER,
    diagnostics_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

ALTER TABLE request_content_guard_events
    ADD COLUMN IF NOT EXISTS provider_id INTEGER,
    ADD COLUMN IF NOT EXISTS provider_name TEXT,
    ADD COLUMN IF NOT EXISTS provider_model_id INTEGER,
    ADD COLUMN IF NOT EXISTS model_name TEXT,
    ADD COLUMN IF NOT EXISTS requested_model TEXT,
    ADD COLUMN IF NOT EXISTS request_path TEXT,
    ADD COLUMN IF NOT EXISTS is_stream BOOLEAN,
    ADD COLUMN IF NOT EXISTS confidence DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS score_delta INTEGER,
    ADD COLUMN IF NOT EXISTS diagnostics_json TEXT;

CREATE TABLE IF NOT EXISTS request_billing_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE CASCADE,
    trace_id TEXT,
    billing_event_id TEXT,
    billing_stage TEXT NOT NULL,
    token_source TEXT,
    prompt_tokens INTEGER,
    completion_tokens INTEGER,
    cache_read_tokens INTEGER,
    cache_write_tokens INTEGER,
    prompt_cost DOUBLE PRECISION,
    completion_cost DOUBLE PRECISION,
    total_cost DOUBLE PRECISION,
    balance_before DOUBLE PRECISION,
    balance_after DOUBLE PRECISION,
    attempt_count INTEGER,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS exception_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    event_type TEXT NOT NULL DEFAULT 'exception',
    event_name TEXT NOT NULL,
    trace_id TEXT,
    correlation_id TEXT,
    module TEXT,
    severity TEXT NOT NULL DEFAULT 'danger',
    actor_type TEXT,
    actor_id TEXT,
    source_ip TEXT,
    result TEXT NOT NULL DEFAULT 'failed',
    exception_type TEXT NOT NULL,
    status_code INTEGER,
    error_code TEXT,
    message TEXT,
    handler_name TEXT,
    request_path TEXT,
    method TEXT,
    is_external_v1 BOOLEAN NOT NULL DEFAULT FALSE,
    stack_hash TEXT,
    stack_excerpt TEXT,
    detail_json TEXT,
    occurred_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS health_check_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL UNIQUE,
    trigger_type TEXT NOT NULL,
    scope_type TEXT NOT NULL,
    scope_id TEXT,
    phase_keys_json TEXT,
    started_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai'),
    finished_at TIMESTAMP,
    duration_ms INTEGER,
    total_probes INTEGER NOT NULL DEFAULT 0,
    success_probes INTEGER NOT NULL DEFAULT 0,
    failed_probes INTEGER NOT NULL DEFAULT 0,
    overall_result TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS health_probe_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL,
    run_id TEXT,
    provider_id INTEGER,
    provider_model_id INTEGER,
    model_name TEXT,
    probe_type TEXT NOT NULL,
    endpoint_path TEXT,
    protocol_type TEXT,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    status_code INTEGER,
    latency_ms INTEGER,
    error_code TEXT,
    capability_result_json TEXT,
    content_guard_result_json TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

ALTER TABLE health_probe_events
    ADD COLUMN IF NOT EXISTS request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS token_finalize_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL,
    queue_source TEXT NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    usage_before_json TEXT,
    usage_after_json TEXT,
    token_source TEXT,
    enable_usage_fill BOOLEAN,
    result TEXT NOT NULL,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS billing_process_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_log_id INTEGER REFERENCES request_logs(id) ON DELETE SET NULL,
    api_client_key_id INTEGER,
    user_account_id INTEGER,
    pricing_source TEXT,
    pricing_snapshot_json TEXT,
    cost_snapshot_json TEXT,
    balance_delta DOUBLE PRECISION,
    balance_after DOUBLE PRECISION,
    billing_status TEXT NOT NULL,
    billing_record_id INTEGER,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS background_job_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_run_id TEXT NOT NULL,
    job_name TEXT NOT NULL,
    trigger_type TEXT NOT NULL DEFAULT 'scheduler',
    lock_key TEXT,
    lock_status TEXT,
    status TEXT NOT NULL,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    duration_ms INTEGER,
    processed_count INTEGER,
    success_count INTEGER,
    failed_count INTEGER,
    result_summary_json TEXT,
    error TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS user_operation_audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_account_id INTEGER,
    username TEXT,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT,
    entity_name TEXT,
    summary TEXT NOT NULL,
    detail_json TEXT,
    source_ip TEXT,
    trace_id TEXT,
    result TEXT NOT NULL DEFAULT 'success',
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

CREATE TABLE IF NOT EXISTS asset_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id INTEGER,
    asset_event_type TEXT NOT NULL,
    actor_type TEXT NOT NULL,
    actor_id TEXT,
    filename TEXT,
    content_type TEXT,
    file_size_bytes INTEGER,
    sha256_prefix TEXT,
    sha256_hex TEXT,
    storage_scope TEXT NOT NULL,
    result TEXT NOT NULL DEFAULT 'success',
    error TEXT,
    trace_id TEXT,
    request_log_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Shanghai')
);

ALTER TABLE asset_events
    ADD COLUMN IF NOT EXISTS sha256_hex TEXT;

CREATE INDEX IF NOT EXISTS ix_request_auth_events_request_log_id ON request_auth_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_trace_id ON request_auth_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_auth_result ON request_auth_events (auth_result);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_api_client_key_id ON request_auth_events (api_client_key_id);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_user_account_id ON request_auth_events (user_account_id);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_error_code ON request_auth_events (error_code);
CREATE INDEX IF NOT EXISTS ix_request_auth_events_created_at ON request_auth_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_validation_events_request_log_id ON request_validation_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_validation_events_trace_id ON request_validation_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_validation_events_validation_stage ON request_validation_events (validation_stage);
CREATE INDEX IF NOT EXISTS ix_request_validation_events_passed ON request_validation_events (passed);
CREATE INDEX IF NOT EXISTS ix_request_validation_events_error_code ON request_validation_events (error_code);
CREATE INDEX IF NOT EXISTS ix_request_validation_events_created_at ON request_validation_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_model_permission_events_request_log_id ON request_model_permission_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_model_permission_events_trace_id ON request_model_permission_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_model_permission_events_requested_model ON request_model_permission_events (requested_model);
CREATE INDEX IF NOT EXISTS ix_request_model_permission_events_permission_result ON request_model_permission_events (permission_result);
CREATE INDEX IF NOT EXISTS ix_request_model_permission_events_created_at ON request_model_permission_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_route_decision_events_request_log_id ON request_route_decision_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_route_decision_events_trace_id ON request_route_decision_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_route_decision_events_selected_provider_id ON request_route_decision_events (selected_provider_id);
CREATE INDEX IF NOT EXISTS ix_request_route_decision_events_created_at ON request_route_decision_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_request_log_id ON request_provider_attempt_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_trace_id ON request_provider_attempt_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_provider_id ON request_provider_attempt_events (provider_id);
CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_result ON request_provider_attempt_events (result);
CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_error_code ON request_provider_attempt_events (error_code);
CREATE INDEX IF NOT EXISTS ix_request_provider_attempt_events_created_at ON request_provider_attempt_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_upstream_response_events_request_log_id ON request_upstream_response_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_upstream_response_events_provider_attempt_event_id ON request_upstream_response_events (provider_attempt_event_id);
CREATE INDEX IF NOT EXISTS ix_request_upstream_response_events_trace_id ON request_upstream_response_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_upstream_response_events_created_at ON request_upstream_response_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_stream_events_request_log_id ON request_stream_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_stream_events_trace_id ON request_stream_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_stream_events_stream_result ON request_stream_events (stream_result);
CREATE INDEX IF NOT EXISTS ix_request_stream_events_created_at ON request_stream_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_error_response_events_request_log_id ON request_error_response_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_error_response_events_trace_id ON request_error_response_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_error_response_events_error_code ON request_error_response_events (error_code);
CREATE INDEX IF NOT EXISTS ix_request_error_response_events_category ON request_error_response_events (category);
CREATE INDEX IF NOT EXISTS ix_request_error_response_events_created_at ON request_error_response_events (created_at);

CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_request_log_id ON request_content_guard_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_trace_id ON request_content_guard_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_id ON request_content_guard_events (provider_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_model_id ON request_content_guard_events (provider_model_id);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_model_name ON request_content_guard_events (model_name);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_request_path ON request_content_guard_events (request_path);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_is_stream ON request_content_guard_events (is_stream);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_guard_stage ON request_content_guard_events (guard_stage);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_guard_result ON request_content_guard_events (guard_result);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_risk_level ON request_content_guard_events (risk_level);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_created_at ON request_content_guard_events (created_at);
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_provider_created_result
    ON request_content_guard_events (provider_id, created_at, guard_result)
    WHERE guard_result IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_request_content_guard_events_risk_provider_created
    ON request_content_guard_events (risk_level, provider_id, created_at)
    WHERE risk_level IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_request_billing_events_request_log_id ON request_billing_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_request_billing_events_trace_id ON request_billing_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_request_billing_events_billing_event_id ON request_billing_events (billing_event_id);
CREATE INDEX IF NOT EXISTS ix_request_billing_events_billing_stage ON request_billing_events (billing_stage);
CREATE INDEX IF NOT EXISTS ix_request_billing_events_created_at ON request_billing_events (created_at);

CREATE INDEX IF NOT EXISTS ix_exception_events_event_id ON exception_events (event_id);
CREATE INDEX IF NOT EXISTS ix_exception_events_event_name ON exception_events (event_name);
CREATE INDEX IF NOT EXISTS ix_exception_events_trace_id ON exception_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_exception_events_correlation_id ON exception_events (correlation_id);
CREATE INDEX IF NOT EXISTS ix_exception_events_module ON exception_events (module);
CREATE INDEX IF NOT EXISTS ix_exception_events_severity ON exception_events (severity);
CREATE INDEX IF NOT EXISTS ix_exception_events_result ON exception_events (result);
CREATE INDEX IF NOT EXISTS ix_exception_events_exception_type ON exception_events (exception_type);
CREATE INDEX IF NOT EXISTS ix_exception_events_error_code ON exception_events (error_code);
CREATE INDEX IF NOT EXISTS ix_exception_events_request_path ON exception_events (request_path);
CREATE INDEX IF NOT EXISTS ix_exception_events_is_external_v1 ON exception_events (is_external_v1);
CREATE INDEX IF NOT EXISTS ix_exception_events_stack_hash ON exception_events (stack_hash);
CREATE INDEX IF NOT EXISTS ix_exception_events_occurred_at ON exception_events (occurred_at);

CREATE INDEX IF NOT EXISTS ix_health_check_runs_run_id ON health_check_runs (run_id);
CREATE INDEX IF NOT EXISTS ix_health_check_runs_trigger_type ON health_check_runs (trigger_type);
CREATE INDEX IF NOT EXISTS ix_health_check_runs_scope_type ON health_check_runs (scope_type);
CREATE INDEX IF NOT EXISTS ix_health_check_runs_scope_id ON health_check_runs (scope_id);
CREATE INDEX IF NOT EXISTS ix_health_check_runs_started_at ON health_check_runs (started_at);
CREATE INDEX IF NOT EXISTS ix_health_check_runs_overall_result ON health_check_runs (overall_result);

CREATE INDEX IF NOT EXISTS ix_health_probe_events_request_log_id ON health_probe_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_run_id ON health_probe_events (run_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_provider_id ON health_probe_events (provider_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_provider_model_id ON health_probe_events (provider_model_id);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_probe_type ON health_probe_events (probe_type);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_success ON health_probe_events (success);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_error_code ON health_probe_events (error_code);
CREATE INDEX IF NOT EXISTS ix_health_probe_events_created_at ON health_probe_events (created_at);

CREATE INDEX IF NOT EXISTS ix_token_finalize_events_request_log_id ON token_finalize_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_token_finalize_events_queue_source ON token_finalize_events (queue_source);
CREATE INDEX IF NOT EXISTS ix_token_finalize_events_result ON token_finalize_events (result);
CREATE INDEX IF NOT EXISTS ix_token_finalize_events_created_at ON token_finalize_events (created_at);

CREATE INDEX IF NOT EXISTS ix_billing_process_events_request_log_id ON billing_process_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_billing_process_events_api_client_key_id ON billing_process_events (api_client_key_id);
CREATE INDEX IF NOT EXISTS ix_billing_process_events_user_account_id ON billing_process_events (user_account_id);
CREATE INDEX IF NOT EXISTS ix_billing_process_events_billing_status ON billing_process_events (billing_status);
CREATE INDEX IF NOT EXISTS ix_billing_process_events_billing_record_id ON billing_process_events (billing_record_id);
CREATE INDEX IF NOT EXISTS ix_billing_process_events_created_at ON billing_process_events (created_at);

CREATE INDEX IF NOT EXISTS ix_background_job_events_job_run_id ON background_job_events (job_run_id);
CREATE INDEX IF NOT EXISTS ix_background_job_events_job_name ON background_job_events (job_name);
CREATE INDEX IF NOT EXISTS ix_background_job_events_trigger_type ON background_job_events (trigger_type);
CREATE INDEX IF NOT EXISTS ix_background_job_events_lock_status ON background_job_events (lock_status);
CREATE INDEX IF NOT EXISTS ix_background_job_events_status ON background_job_events (status);
CREATE INDEX IF NOT EXISTS ix_background_job_events_started_at ON background_job_events (started_at);
CREATE INDEX IF NOT EXISTS ix_background_job_events_created_at ON background_job_events (created_at);

CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_user_account_id ON user_operation_audit_logs (user_account_id);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_username ON user_operation_audit_logs (username);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_action ON user_operation_audit_logs (action);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_entity_type ON user_operation_audit_logs (entity_type);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_entity_id ON user_operation_audit_logs (entity_id);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_trace_id ON user_operation_audit_logs (trace_id);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_result ON user_operation_audit_logs (result);
CREATE INDEX IF NOT EXISTS ix_user_operation_audit_logs_created_at ON user_operation_audit_logs (created_at);

CREATE INDEX IF NOT EXISTS ix_asset_events_asset_id ON asset_events (asset_id);
CREATE INDEX IF NOT EXISTS ix_asset_events_asset_event_type ON asset_events (asset_event_type);
CREATE INDEX IF NOT EXISTS ix_asset_events_actor_type ON asset_events (actor_type);
CREATE INDEX IF NOT EXISTS ix_asset_events_actor_id ON asset_events (actor_id);
CREATE INDEX IF NOT EXISTS ix_asset_events_storage_scope ON asset_events (storage_scope);
CREATE INDEX IF NOT EXISTS ix_asset_events_result ON asset_events (result);
CREATE INDEX IF NOT EXISTS ix_asset_events_trace_id ON asset_events (trace_id);
CREATE INDEX IF NOT EXISTS ix_asset_events_request_log_id ON asset_events (request_log_id);
CREATE INDEX IF NOT EXISTS ix_asset_events_created_at ON asset_events (created_at);
