from app.utils.timezone import now_beijing
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base
from app.utils.content_guard_config import content_guard_default


class AppSetting(Base):
    __tablename__ = "app_settings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=1)
    global_timeout_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=30000)
    global_max_retries: Mapped[int] = mapped_column(Integer, nullable=False, default=2)
    route_exhausted_retry_max_wait_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=600)
    route_exhausted_retry_infinite_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    trusted_providers_only: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    route_strategy: Mapped[str] = mapped_column(Text, nullable=False, default="availability_first")
    route_health_gate_mode: Mapped[str] = mapped_column(Text, nullable=False, default="permissive")
    max_candidate_count: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    route_candidate_expand_count: Mapped[int] = mapped_column(Integer, nullable=False, default=5)
    global_max_request_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_v1_request_body_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=20971520)
    max_v1_chat_request_body_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_v1_responses_request_body_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    long_output_stream_threshold_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=8192)
    max_non_stream_response_body_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=20971520)
    stream_token_capture_max_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=1048576)
    max_logged_metadata_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=1024)
    content_guard_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enabled"))
    content_guard_precheck_auto_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_precheck_auto_enabled"))
    content_guard_block_on_high_risk: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_block_on_high_risk"))
    content_guard_probe_interval_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_probe_interval_sec"))
    content_guard_json_probe_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_json_probe_enabled"))
    content_guard_probe_protocol_type: Mapped[str] = mapped_column(Text, nullable=False, default=content_guard_default("content_guard_probe_protocol_type"))
    content_guard_max_scan_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_max_scan_bytes"))
    content_guard_stream_buffer_max_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_stream_buffer_max_bytes"))
    content_guard_low_trust_requires_buffer: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_low_trust_requires_buffer"))
    content_guard_rules_json: Mapped[str] = mapped_column(Text, nullable=False, default=content_guard_default("content_guard_rules_json"))
    content_guard_high_risk_strategy: Mapped[str] = mapped_column(Text, nullable=False, default=content_guard_default("content_guard_high_risk_strategy"))
    content_guard_max_detection_delay_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_max_detection_delay_ms"))
    content_guard_stream_mode: Mapped[str] = mapped_column(Text, nullable=False, default=content_guard_default("content_guard_stream_mode"))
    content_guard_url_check_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_url_check_enabled"))
    content_guard_url_allowlist_json: Mapped[str] = mapped_column(Text, nullable=False, default=content_guard_default("content_guard_url_allowlist_json"))
    content_guard_async_review_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_async_review_enabled"))
    content_guard_high_risk_confidence_threshold: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_high_risk_confidence_threshold"))
    content_guard_enhanced_detection_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enhanced_detection_enabled"))
    content_guard_enhanced_illegal_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enhanced_illegal_enabled"))
    content_guard_enhanced_ad_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enhanced_ad_enabled"))
    content_guard_enhanced_custom_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enhanced_custom_enabled"))
    content_guard_enhanced_obfuscation_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=content_guard_default("content_guard_enhanced_obfuscation_enabled"))
    content_guard_enhanced_threshold: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_enhanced_threshold"))
    content_guard_enhanced_context_window_chars: Mapped[int] = mapped_column(Integer, nullable=False, default=content_guard_default("content_guard_enhanced_context_window_chars"))
    circuit_breaker_threshold: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    auto_health_check: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    health_check_interval_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=300)
    recovery_probe_interval_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=30)
    probe_rate_limit_per_minute: Mapped[int] = mapped_column(Integer, nullable=False, default=4)
    probe_type_rate_limit_per_minute: Mapped[int] = mapped_column(Integer, nullable=False, default=4)
    enable_token_logging: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    enable_payload_logging: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    enable_stream_response_persist: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    mask_sensitive_fields: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    max_logged_body_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=16384)
    allow_public_user_registration: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    request_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    admin_audit_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    request_child_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    exception_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    health_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    billing_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    background_job_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    user_operation_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    asset_log_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    alert_event_retention_days: Mapped[int] = mapped_column(Integer, nullable=False, default=7)
    route_candidate_cache_ttl_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    model_list_cache_ttl_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=15)
    provider_status_cache_ttl_sec: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    async_request_logging: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    global_qps_limit: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    global_rpm_limit: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    account_qps_limit: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    account_rpm_limit: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    global_max_active_requests: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    global_max_active_streams: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    api_key_max_active_requests: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    api_key_max_active_streams: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    account_max_active_requests: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    account_max_active_streams: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    provider_max_active_requests: Mapped[int] = mapped_column(Integer, nullable=False, default=20)
    provider_max_active_streams: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    concurrency_lease_ttl_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=900)
    stream_connect_timeout_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    stream_first_token_timeout_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=60)
    stream_idle_timeout_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=120)
    stream_max_duration_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=600)
    responses_chat_adapter_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    responses_chat_adapter_storage_type: Mapped[str] = mapped_column(Text, nullable=False, default="database")
    responses_chat_adapter_ttl_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=86400)
    responses_chat_adapter_model_map_json: Mapped[str] = mapped_column(Text, nullable=False, default="")
    responses_chat_adapter_max_tool_rounds: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    responses_chat_adapter_web_search_enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    responses_chat_adapter_search_proxy_url: Mapped[str] = mapped_column(Text, nullable=False, default="")
    responses_chat_adapter_upstream_base_url: Mapped[str] = mapped_column(Text, nullable=False, default="")
    responses_chat_adapter_upstream_api_key: Mapped[str] = mapped_column(Text, nullable=False, default="")
    responses_chat_adapter_upstreams_json: Mapped[str] = mapped_column(Text, nullable=False, default="")
    responses_chat_adapter_context_window_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=128000)
    responses_chat_adapter_snapshot_max_bytes: Mapped[int] = mapped_column(Integer, nullable=False, default=1048576)
    responses_chat_adapter_db_cleanup_interval_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=21600)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False, default=now_beijing)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=now_beijing, onupdate=now_beijing
    )
